### PR TITLE
Finish adding Flow types everywhere

### PR DESCRIPTION
**Pull request by Stephen2**

### CODE REVIEW

**Comment by Stephen2** [comment]
What I'm trying to figure out is the correct way to set Props for TodoApp.js

Running `yarn run flow` locally from this branch will show:
```
Cannot create TodoApp element because:
 • property $refType is missing in object type [1] but exists in TodoApp_user [2] in property user.
 • property id is missing in object type [1] but exists in TodoApp_user [2] in property user.
 • property totalCount is missing in object type [1] but exists in TodoApp_user [2] in property user.
 • property userId is missing in object type [1] but exists in TodoApp_user [2] in property user.

     js/app.js
     71│       }}
     72│       render={({error, props}: {error: ?Error, props: ?appQueryResponse}) => {
     73│         if (props && props.user) {
     74│           return <TodoApp user={props.user} />;
     75│         } else if (error) {
     76│           return <div>{error.message}</div>;
     77│         }

     __generated__/relay/appQuery.graphql.js
 [1] 17│   +user: ?{|
     18│     +$fragmentRefs: TodoApp_user$ref
     19│   |}

     js/components/TodoApp.js
 [2] 26│   +user: TodoApp_user,
```

**Comment by kassens** [comment]
The definition of flow-typed isn't right.

This commit fixes the container issue for me: https://github.com/relayjs/relay-examples/commit/925ab817c6a78f039debe00eea24db337355e684

Feel free to contribute that change upstream to flow-typed!

**Comment by kassens** [comment]
Boom, so good!

**Comment by alloy** [comment]
Awesome, great work, folks! 👏

**Pull request merged**
