### PR TITLE
mv todo-modern todo-compat

### PR DESCRIPTION
**Pull request by robrichard**
The current todo-modern example is actually using `react-relay/compat` and a few modules from `react-relay/classic` (Store is one of them). This PR renames the directory to todo-compat to accurately reflect what it's doing. I'm also working on adding an example that only uses the relay modern api but I'm currently blocked by https://github.com/facebook/relay/issues/1665

### CODE REVIEW

**Comment by eugene1g** [comment]
I also put together a quick update to use Relay Modern directly at https://github.com/relayjs/relay-examples/compare/master...eugene1g:master

**Comment by alangenfeld** [comment]
Sorry I overlooked this. The intent of the todo-modern example was to incrementally upgrade it through compat all the way to modern. I just finished updating it all the way.

If you think its valuable we can have a todo-compat that is a snapshot of todo-modern mid migration.

**Comment by edwardaa** [comment]
Hi, myabe it's time to remove compact mode in .babalrc:
```diff
index 2213dc4..18be280 100644
--- a/todo-modern/.babelrc
+++ b/todo-modern/.babelrc
@@ -1,7 +1,7 @@
 {
   "passPerPreset": true,
   "plugins": [
-    ["relay", {"compat": true, "schema": "data/schema.graphql"}],
+    "relay",
     "transform-runtime"
   ],
   "presets": [
```

**Comment by alangenfeld** [comment]
good catch, removed in b51829b9aa2c2f526d9d7bbe1fdb6221750f8d93

**Pull request closed without merging**
